<template>
  <div class="forge-message-submit" :class="{ 'is-submitted': isSubmitted }">
    <div class="forge-message-submit-hint">
        <template v-if="isSubmitted">这部分内容已提交给 Forge 分析。如需修改请发新消息补充。</template>
        <template v-else>这条消息里的待填内容会一起提交给 Forge。</template>
    </div>
    <button class="forge-message-submit-btn" :disabled="isProcessing || isSubmitted" @click="submitForm">
      <template v-if="isSubmitted">已提交</template>
      <template v-else>{{ buttonLabel }}</template>
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useCardMakerStore } from '../CardMakerStore';
import { useForgeStore } from '../../../stores/useForgeStore';

const props = defineProps<{
    formId?: string;
    messageId?: string;
    label?: string;
    autoGenerated?: boolean;
}>();

const store = useCardMakerStore();
const forgeStore = useForgeStore();
const targetId = computed(() => props.formId || props.messageId || '');
const buttonLabel = computed(() => {
    if (!targetId.value) return props.label || '提交并继续';
    return store.resolveSubmitLabel(targetId.value, props.label || '提交并继续');
});

const isSubmitted = computed(() => {
    if (props.formId && store.structuredState.forms[props.formId]) {
        return Boolean(store.structuredState.forms[props.formId]?.lastSubmittedAt);
    }
    if (!targetId.value) return false;
    return store.isScopeSubmitted(targetId.value);
});

const isProcessing = computed(() => store.isGenerating || forgeStore.isProcessing);

const submitForm = () => {
    console.log(`[Forge-Submit] 触发消息提交按钮点击 (formId: "${props.formId}")。`, {
        isSubmitted: isSubmitted.value,
        isProcessing: isProcessing.value
    });
    if (isSubmitted.value || isProcessing.value) {
        console.warn('[Forge-Submit] 点击被拦截：已提交或正在处理中。');
        return;
    }
    if (!targetId.value) {
        console.warn('[Forge-Submit] 点击被拦截：缺少目标作用域。');
        return;
    }
    if (props.label) {
        store.rememberSubmitConfig(targetId.value, props.label);
    }
    void store.submitStructuredForm(targetId.value);
};
</script>

<style scoped>
.forge-message-submit {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-wrap: wrap;
  padding: 12px 14px;
  border-radius: 16px;
  border: 1px dashed rgba(var(--lw-primary-rgb), 0.2);
  background: rgba(var(--lw-primary-rgb), 0.04);
}

.forge-message-submit-hint {
  font-size: 11px;
  line-height: 1.6;
  color: var(--lw-text-muted);
}

.forge-message-submit-btn {
  border-radius: 12px;
  border: 1px solid #111111;
  background: #111111;
  color: var(--lw-text-inverse);
  padding: 9px 12px;
  font-size: 12px;
  font-weight: 700;
  cursor: pointer;
}

.forge-message-submit-btn:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}
</style>
