<template>
  <LuminaPanel variant="elevated" padding="sm" class="tw:flex tw:flex-wrap tw:items-center tw:justify-between tw:gap-3 tw:border-dashed">
    <div class="tw:text-xs tw:leading-5 tw:text-lw-text-muted tw:text-pretty">
        <template v-if="isSubmitted">这部分内容已提交给 Forge 分析。如需修改请发新消息补充。</template>
        <template v-else>这条消息里的待填内容会一起提交给 Forge。</template>
    </div>
    <LuminaButton tone="primary" :disabled="isProcessing || isSubmitted" @click="submitForm">
      <template v-if="isSubmitted">已提交</template>
      <template v-else>{{ buttonLabel }}</template>
    </LuminaButton>
  </LuminaPanel>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useCardMakerStore } from '../CardMakerStore.js';
import { useForgeStore } from '../../../stores/useForgeStore.js';
import { LuminaButton, LuminaPanel } from '../../../ui/primitives';

const props = defineProps<{
    formId?: string;
    messageId?: string;
    label?: string;
    autoGenerated?: boolean;
}>();

const store = useCardMakerStore();
const forgeStore = useForgeStore();
const targetId = computed(() => props.formId || props.messageId || '');
const buttonLabel = computed(() => {
    if (!targetId.value) return props.label || '提交并继续';
    return store.resolveSubmitLabel(targetId.value, props.label || '提交并继续');
});

const isSubmitted = computed(() => {
    if (props.formId && store.structuredState.forms[props.formId]) {
        return Boolean(store.structuredState.forms[props.formId]?.lastSubmittedAt);
    }
    if (!targetId.value) return false;
    return store.isScopeSubmitted(targetId.value);
});

const isProcessing = computed(() => store.isGenerating || forgeStore.isProcessing);

const submitForm = () => {
    console.log(`[Forge-Submit] 触发消息提交按钮点击 (formId: "${props.formId}")。`, {
        isSubmitted: isSubmitted.value,
        isProcessing: isProcessing.value
    });
    if (isSubmitted.value || isProcessing.value) {
        console.warn('[Forge-Submit] 点击被拦截：已提交或正在处理中。');
        return;
    }
    if (!targetId.value) {
        console.warn('[Forge-Submit] 点击被拦截：缺少目标作用域。');
        return;
    }
    if (props.label) {
        store.rememberSubmitConfig(targetId.value, props.label);
    }
    void store.submitStructuredForm(targetId.value);
};
</script>
