[package]
name = "luminaweave-client"
version = "0.1.0"
description = "LuminaWeave Tauri Client"
# authors = ["LuminaWeave"]
license = "AGPL-3.0-only"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix makes the lib name unique and avoids conflicts with the bin name on Windows.
name = "luminaweave_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
