export const FORGE_LAYER_ADVANCE_REQUESTED = 'FORGE_LAYER_ADVANCE_REQUESTED';
export const FORGE_FORM_RESULT_SUBMITTED = 'FORGE_FORM_RESULT_SUBMITTED';
export const FORGE_WORKSPACE_FREEZE_REQUESTED = 'FORGE_WORKSPACE_FREEZE_REQUESTED';
export const FORGE_PLANNER_INTENT_APPLIED = 'FORGE_PLANNER_INTENT_APPLIED';
